import Navbar from '@/components/navbar/Navbar'
import { ContextProvider } from "../components/Clients";
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          {/* <Navbar /> */}
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
